/*  helloparam.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/utsname.h>
/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR("sed");
MODULE_DESCRIPTION("helloparam - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "helloparam"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
static char *whom="world";
module_param(whom, charp, 0);

static int howmany = 1;
module_param(howmany, int, 0);

//static struct utsname *uts;
static char ver;

static int __init helloparam_init(void)
{
	int i;
//	ver=utsname()->release;
	for (i=0; i < howmany; i++)
		pr_alert("(%d) Hello, %s\n", i, whom);
		printk("version kernel: %s\n", utsname()->release);
	return 0;

//	printk("<1>Hello module world.\n");
//	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
//	       mystr);

//	return platform_driver_register(&helloparam_driver);
}


static void __exit helloparam_exit(void)
{
	pr_alert("Goodbye, cruel %s\n", whom);
//	platform_driver_unregister(&helloparam_driver);
//	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(helloparam_init);
module_exit(helloparam_exit);
